<h1>Napisz do nas wiadomość!</h1>
<form action="mail.php" method="post">
  <label for="fname">Imię</label>
  <input type="text" id="fname" name="firstname" placeholder="Twoję imię...">

  <label for="email">E-Mail</label>
  <input type="text" id="email" name="email" placeholder="Twój email...">

  <label for="country">Kraj</label>
  <select id="country" name="country">
    <option value="AF">Afganistan</option>
    <option value="AX">Wyspy Alandzkie</option>
    <option value="AL">Albania</option>
    <option value="DZ">Algieria</option>
    <option value="AS">Samoa Amerykańskie</option>
    <option value="AD">Andora</option>
    <option value="AO">Angola</option>
    <option value="AI">Anguilla</option>
    <option value="AQ">Antarktyda</option>
    <option value="AG">Antigua i Barbuda</option>
    <option value="AR">Argentyna</option>
    <option value="AM">Armenia</option>
    <option value="AW">Aruba</option>
    <option value="AU">Australia</option>
    <option value="AT">Austria</option>
    <option value="AZ">Azerbejdżan</option>
    <option value="BS">Bahamy</option>
    <option value="BH">Bahrajn</option>
    <option value="BD">Bangladesz</option>
    <option value="BB">Barbados</option>
    <option value="BY">Białoruś</option>
    <option value="BE">Belgia</option>
    <option value="BZ">Belize</option>
    <option value="BJ">Benin</option>
    <option value="BM">Bermudy</option>
    <option value="BT">Bhutan</option>
    <option value="BO">Boliwia</option>
    <option value="BQ">Bonaire, Sint Eustatius i Saba</option>
    <option value="BA">Bośnia i Hercegowina</option>
    <option value="BW">Botswana</option>
    <option value="BV">Wyspa Bouveta</option>
    <option value="BR">Brazylia</option>
    <option value="IO">Brytyjskie Terytorium Oceanu Indyjskiego</option>
    <option value="BN">Brunei Darussalam</option>
    <option value="BG">Bułgaria</option>
    <option value="BF">Burkina Faso</option>
    <option value="BI">Burundi</option>
    <option value="KH">Kambodża</option>
    <option value="CM">Kamerun</option>
    <option value="CA">Kanada</option>
    <option value="CV">Wyspy Zielonego Przylądka</option>
    <option value="KY">Kajmany</option>
    <option value="CF">Republika Środkowoafrykańska</option>
    <option value="TD">Czad</option>
    <option value="CL">Chile</option>
    <option value="CN">Chiny</option>
    <option value="CX">Wyspa Bożego Narodzenia</option>
    <option value="CC">Wyspy Kokosowe (Keelinga)</option>
    <option value="CO">Kolumbia</option>
    <option value="KM">Komory</option>
    <option value="CG">Kongo</option>
    <option value="CD">Kongo, Demokratyczna Republika Konga</option>
    <option value="CK">Wyspy Cooka</option>
    <option value="CR">Kostaryka</option>
    <option value="CI">Wybrzeże Kości Słoniowej</option>
    <option value="HR">Chorwacja</option>
    <option value="CU">Kuba</option>
    <option value="CW">Curacao</option>
    <option value="CY">Cypr</option>
    <option value="CZ">Republika Czeska</option>
    <option value="DK">Dania</option>
    <option value="DJ">Dżibuti</option>
    <option value="DM">Dominika</option>
    <option value="DO">Republika Dominikany</option>
    <option value="EC">Ekwador</option>
    <option value="EG">Egipt</option>
    <option value="SV">Salwador</option>
    <option value="GQ">Gwinea Równikowa</option>
    <option value="ER">Erytrea</option>
    <option value="EE">Estonia</option>
    <option value="ET">Etiopia</option>
    <option value="FK">Falklandy (Malwiny)</option>
    <option value="FO">Wyspy Owcze</option>
    <option value="FJ">Fidżi</option>
    <option value="FI">Finlandia</option>
    <option value="FR">Francja</option>
    <option value="GF">Gujana Francuska</option>
    <option value="PF">Polinezja Francuska</option>
    <option value="TF">Francuskie Terytoria Południowe</option>
    <option value="GA">Gabon</option>
    <option value="GM">Gambia</option>
    <option value="GE">Gruzja</option>
    <option value="DE">Niemcy</option>
    <option value="GH">Ghana</option>
    <option value="GI">Gibraltar</option>
    <option value="GR">Grecja</option>
    <option value="GL">Grenlandia</option>
    <option value="GD">Grenada</option>
    <option value="GP">Gwadelupa</option>
    <option value="GU">Guam</option>
    <option value="GT">Gwatemala</option>
    <option value="GG">Guernsey</option>
    <option value="GN">Gwinea</option>
    <option value="GW">Gwinea Bissau</option>
    <option value="GY">Gujana</option>
    <option value="HT">Haiti</option>
    <option value="HM">Wyspy Heard i McDonalda</option>
    <option value="VA">Stolica Apostolska (Państwo Watykańskie)</option>
    <option value="HN">Honduras</option>
    <option value="HK">Hongkong</option>
    <option value="HU">Węgry</option>
    <option value="IS">Islandia</option>
    <option value="IN">Indie</option>
    <option value="ID">Indonezja</option>
    <option value="IR">Iran</option>
    <option value="IQ">Irak</option>
    <option value="IE">Irlandia</option>
    <option value="IM">Wyspa Man</option>
    <option value="IL">Izrael</option>
    <option value="IT">Włochy</option>
    <option value="JM">Jamajka</option>
    <option value="JP">Japonia</option>
    <option value="JE">Golf</option>
    <option value="JO">Jordania</option>
    <option value="KZ">Kazachstan</option>
    <option value="KE">Kenia</option>
    <option value="KI">Kiribati</option>
    <option value="KP">Koreańska Republika Ludowo-Demokratyczna</option>
    <option value="KR">Republika Korei</option>
    <option value="XK">Kosowo</option>
    <option value="KW">Kuwejt</option>
    <option value="KG">Kirgistan</option>
    <option value="LA">Laotańska Republika Ludowo-Demokratyczna</option>
    <option value="LV">Łotwa</option>
    <option value="LB">Liban</option>
    <option value="LS">Lesotho</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libijska Arabska Dżamahirija</option>
    <option value="LI">Liechtenstein</option>
    <option value="LT">Litwa</option>
    <option value="LU">Luksemburg</option>
    <option value="MO">Makao</option>
    <option value="MK">Macedonia, Była Jugosłowiańska Republika</option>
    <option value="MG">Madagaskar</option>
    <option value="MW">Malawi</option>
    <option value="MY">Malezja</option>
    <option value="MV">Malediwy</option>
    <option value="ML">Mali</option>
    <option value="MT">Malta</option>
    <option value="MH">Wyspy Marshalla</option>
    <option value="MQ">Martynika</option>
    <option value="MR">Mauretania</option>
    <option value="MU">Mauritius</option>
    <option value="YT">Majotta</option>
    <option value="MX">Meksyk</option>
    <option value="FM">Mikronezja, Sfederowane Stany</option>
    <option value="MD">Mołdawia, Republika</option>
    <option value="MC">Monako</option>
    <option value="MN">Mongolia</option>
    <option value="ME">Czarnogóra</option>
    <option value="MS">Montserrat</option>
    <option value="MA">Maroko</option>
    <option value="MZ">Mozambik</option>
    <option value="MM">Myanmar</option>
    <option value="NA">Namibia</option>
    <option value="NR">Nauru</option>
    <option value="NP">Nepal</option>
    <option value="NL">Holandia</option>
    <option value="AN">Antyle Holenderskie</option>
    <option value="NC">Nowa Kaledonia</option>
    <option value="NZ">Nowa Zelandia</option>
    <option value="NI">Nikaragua</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="NU">Niue</option>
    <option value="NF">Wyspa Norfolk</option>
    <option value="MP">Mariany Północne</option>
    <option value="NO">Norwegia</option>
    <option value="OM">Oman</option>
    <option value="PK">Pakistan</option>
    <option value="PW">Palau</option>
    <option value="PS">Teretorium Paleństynskie, Okupowane</option>
    <option value="PA">Panama</option>
    <option value="PG">Papua Nowa Gwinea</option>
    <option value="PY">Paragwaj</option>
    <option value="PE">Peru</option>
    <option value="PH">Filipiny</option>
    <option value="PN">Pitcairn</option>
    <option selected="selected" value="PL">Polska</option>
    <option value="PT">Portugalia</option>
    <option value="PR">Portoryko</option>
    <option value="QA">Katar</option>
    <option value="RE">Zjazd</option>
    <option value="RO">Rumunia</option>
    <option value="RU">Federacja Rosyjska</option>
    <option value="RW">Rwanda</option>
    <option value="BL">Saint Barthelemy</option>
    <option value="SH">Święta Helena</option>
    <option value="KN">Saint Kitts i Nevis</option>
    <option value="LC">święta Lucia</option>
    <option value="MF">święty Marcin</option>
    <option value="PM">Saint-Pierre i Miquelon</option>
    <option value="VC">Saint Vincent i Grenadyny</option>
    <option value="WS">Samoa</option>
    <option value="SM">San Marino</option>
    <option value="ST">Wyspy Świętego Tomasza i Książęca</option>
    <option value="SA">Arabia Saudyjska</option>
    <option value="SN">Senegal</option>
    <option value="RS">Serbia</option>
    <option value="CS">Serbia i Czarnogóra</option>
    <option value="SC">Seszele</option>
    <option value="SL">Sierra Leone</option>
    <option value="SG">Singapur</option>
    <option value="SX">St Martin</option>
    <option value="SK">Słowacja</option>
    <option value="SI">Słowenia</option>
    <option value="SB">Wyspy Salomona</option>
    <option value="SO">Somali</option>
    <option value="ZA">Afryka Południowa</option>
    <option value="GS">Georgia Południowa i Sandwich Południowy</option>
    <option value="SS">Południowy Sudan</option>
    <option value="ES">Hiszpania</option>
    <option value="LK">Sri Lanka</option>
    <option value="SD">Sudan</option>
    <option value="SR">Surinam</option>
    <option value="SJ">Svalbard i Jan Mayen</option>
    <option value="SZ">Suazi</option>
    <option value="SE">Szwecja</option>
    <option value="CH">Szwajcaria</option>
    <option value="SY">Republika Syryjsko-Arabska</option>
    <option value="TW">Tajwan, prowincja Chin</option>
    <option value="TJ">Tadżykistan</option>
    <option value="TZ">Tanzania, Zjednoczona Republika</option>
    <option value="TH">Tajlandia</option>
    <option value="TL">Timor Wschodni</option>
    <option value="TG">Togo</option>
    <option value="TK">Tokelau</option>
    <option value="TO">Tonga</option>
    <option value="TT">Trynidad i Tobago</option>
    <option value="TN">Tunezja</option>
    <option value="TR">Turcja</option>
    <option value="TM">Turkmenia</option>
    <option value="TC">Wyspy Turks i Caicos</option>
    <option value="TV">Tuvalu</option>
    <option value="UG">Uganda</option>
    <option value="UA">Ukraina</option>
    <option value="AE">Zjednoczone Emiraty Arabskie</option>
    <option value="GB">Zjednoczone Królestwo</option>
    <option value="US">Stany Zjednoczone</option>
    <option value="UM">Stany Zjednoczone Dalekie Wyspy Mniejsze</option>
    <option value="UY">Urugwaj</option>
    <option value="UZ">Uzbekistan</option>
    <option value="VU">Vanuatu</option>
    <option value="VE">Wenezuela</option>
    <option value="VN">Viet Nam</option>
    <option value="VG">Wyspy Dziewicze, Brytyjskie</option>
    <option value="VI">Wyspy Dziewicze Stanów Zjednoczonych</option>
    <option value="WF">Wallis i Futuna</option>
    <option value="EH">Sahara Zachodnia</option>
    <option value="YE">Jemen</option>
    <option value="ZM">Zambia</option>
    <option value="ZW">Zimbabwe</option>
  </select>
  <label for="subject">Temat</label>
  <textarea id="subject" name="content" placeholder="Napisz coś" style="height:475px"></textarea>

  <input type="submit" name = "submit" value="Wyślij">
</form>